feat(CA): init CA (Controllable Agent) library
OpenSPG/openspg pull request #184
Opened 2024-03-29 10:02 UTC by mfz-ant

The CA (Controllable Agent) library is designed to streamline the process of computation and scheduling within Python applications. It provides a modular framework that allows for the separation of computation logic from scheduling logic, as well as the ability to interface with remote Large Language Models (LLMs).

2024-03-29 10:41 UTC, leywar requested changes

2024-03-29 10:41 UTC, leywar commented on python/knext/knext/ca/module/llms.py
> +            # 将结果解析为JSON格式
add comments in English.

2024-04-09 06:58 UTC, mfz-ant commented
I have read the CLA Document and I hereby sign the CLA

2024-04-09 10:25 UTC, leywar approved these changes
LGTM

2024-04-10 06:40 UTC, didicout approved these changes

2024-04-10 09:07 UTC, merged