Branch0101
OpenSPG/openspg pull request #43
Opened 2023-12-24 10:14 UTC by J1ers

2023-12-24 12:11 UTC, leywar requested changes

2023-12-24 12:11 UTC, leywar commented on builder/core/src/main/java/com/antgroup/openspg/builder/core/strategy/linking/impl/SearchBasedLinking.java
> +    request.setSize(50);
add global variable for search engine truncation length setting.

2023-12-24 12:11 UTC, leywar commented on builder/runner/local/src/main/java/com/antgroup/openspg/builder/runner/local/LocalBuilderRunner.java
> +    // 构建指标统计，并将构建指标输出到log
Please write comments in English.

2023-12-24 12:11 UTC, leywar commented on builder/runner/local/src/main/java/com/antgroup/openspg/builder/runner/local/LocalBuilderRunner.java
> +  public void execute() throws Exception {
add comments to describe the `execute` process in detail

2023-12-25 01:41 UTC, youdonghai requested changes

2023-12-25 01:41 UTC, youdonghai commented on reasoner/common/src/main/java/com/antgroup/openspg/reasoner/common/graph/vertex/impl/VertexId.java
> +  @Getter private String bizId;
We cannot add the bizId here as this class represents a segment of binary data used as a fixed-length key for RocksDB. Adding the bizId here would result in data from RocksDBGraphState being unable to deserialize the bizId, rendering the entire engine system inoperable.

2023-12-25 12:15 UTC, closed without merging