feat(nn4k): implement openai invoker and local hf executor
OpenSPG/openspg pull request #57
Opened 2024-01-05 07:54 UTC by xionghuaidong

2024-01-05 08:22 UTC, didicout requested changes

2024-01-05 08:22 UTC, didicout commented on python/nn4k/nn4k/utils/class_importing.py
> +    :param name: fully qualified class name, e.g. ``foo.bar.MyClass``
pls unify the doc-string style

2024-01-05 09:03 UTC, xionghuaidong commented on python/nn4k/nn4k/utils/class_importing.py
> +    :param name: fully qualified class name, e.g. ``foo.bar.MyClass``
done

2024-01-05 11:31 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/hugging_face.py
> +            do_sample = False
done

2024-01-05 11:31 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/hugging_face.py
> +        outputs = [
done

2024-01-05 11:31 UTC, xionghuaidong commented on python/nn4k/nn4k/invoker/base.py
> +        nn_invoker = nn_config.get("nn_invoker")
done

2024-01-05 11:32 UTC, xionghuaidong commented on python/nn4k/nn4k/invoker/base.py
> +        nn_name = nn_config.get("nn_name")
done

2024-01-05 11:32 UTC, xionghuaidong commented on python/nn4k/nn4k/invoker/base.py
> +    def submit_inference(self, submit_mode="k8s"):
done

2024-01-05 11:32 UTC, xionghuaidong commented on python/nn4k/nn4k/invoker/base.py
> +        nn_name = get_string_field(self.init_args, "nn_name", "NN model name")
done

2024-01-05 11:32 UTC, xionghuaidong commented on python/nn4k/setup.py
> +    author_email="huaidong.xhd@antgroup.com",
fixed

2024-01-06 03:34 UTC, leywar approved these changes

2024-01-06 03:36 UTC, baifuyu approved these changes
LGTM

2024-01-06 04:12 UTC, merged