feat(knext): add knext feature and refactor some code
OpenSPG/openspg pull request #58
Opened 2024-01-05 18:36 UTC by J1ers

2024-01-05 19:46 UTC, leywar requested changes

2024-01-05 19:46 UTC, leywar commented on python/knext/knext/common/cache.py
> +    def __init__(self, maxsize: int = 500, ttl: int = 60):
pre-define global variables for `maxsize` and `ttl`, and we need to get accurate values of these variables through a set of testing to ensure the stability of `fuse result cache`

2024-01-05 19:46 UTC, leywar commented on python/knext/knext/operator/builtin/auto_prompt.py
> +        self.spg_type_schema_info_en = {"Text": ("文本", None), "Integer": ("整型", None), "Float": ("浮点型", None)}
we should get the Chinese and English definitions of `BasicType`s through SPG Schema API instead of hard coding.

2024-01-05 19:46 UTC, leywar commented on python/knext/knext/operator/builtin/auto_prompt.py
> +            if _type.name in ["Text", "Integer", "Float"]:
the same as above.

2024-01-05 19:46 UTC, leywar commented on python/knext/knext/operator/spg_record.py
> +        self._properties = properties
add verification logic to determine whether each property in `Dict` belongs to the specified `_spg_type_name` SPGType.

2024-01-05 19:46 UTC, leywar commented on python/knext/knext/operator/spg_record.py
> +        self.properties[property_name] = value
the same as above.

2024-01-05 19:46 UTC, leywar commented on python/knext/knext/operator/spg_record.py
> +        self.relations[relation_name + "#" + object_type_name] = value
add verification logic for the existence of the triple `<_spg_type_name, relation_name, object_type_name>` in SPGSchema.

2024-01-05 19:46 UTC, leywar commented on python/knext/knext/operator/spg_record.py
> +            self.relations[relation_name + "#" + object_type_name] = value
the same as above.

2024-01-05 19:46 UTC, leywar commented on python/knext/knext/operator/op.py
> +    ) -> List[SPGRecord]:
Why is the output of the `FuseOp` a `List[SPGRecord]`?  It should be to merge the current `SPGRecord` with an existing `SPGRecord`, right?

2024-01-05 19:46 UTC, leywar commented on python/knext/knext/operator/op.py
> +    def build_next_variables(
do we still need API `build_next_variables`?

2024-01-06 02:54 UTC, xionghuaidong commented
I added commit [align with nn4k interface and remove extra files](https://github.com/OpenSPG/openspg/pull/58/commits/34680793b93785a3eb10e6895502e58f7753e7a0) to:

* align with NN4K interface change
* avoid conflicts when merge with PR #57.

2024-01-06 06:41 UTC, leywar approved these changes
only fixed the fuse problem,  other problems have been postponed to fix

2024-01-06 06:48 UTC, baifuyu approved these changes

2024-01-06 07:55 UTC, merged